version: "3.9"
services:
  frontend:
    build:
      context: '../'
    ports:
      - '127.0.0.1:4100:4000'
    healthcheck:
      test: "wget -nv -t1 --spider 'http://localhost:4000/health' || exit 1"
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 3
  e2e:
    build:
      context: './'
    depends_on:
      - frontend
    volumes:
      - './reports:/home/pwuser/app/reports:w'
      - './playwright-report:/home/pwuser/app/playwright-report:w'
